spring:
  messages:
    encoding: UTF-8
    always-use-message-format: true
  application:
    name: demo
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/study_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root     # DB 아이디
    password: root     # DB 비밀번호
  jpa:
    hibernate:
      ddl-auto: update # DB 스키마 자동 생성 (운영에선 validate 또는 none 사용)
    properties:
      hibernate:
        format_sql: true # SQL 예쁘게 출력
        show_sql: true   # SQL 로그에 
  batch:
    jdbc:
      initialize-schema: always # 스프링 배치 메타 테이블 자동 생성
  mail:
    host: smtp.gmail.com
    port: 587
    username: kbj961117@gmail.com  # 본인 Gmail 계정
    password: *******   # 앱 비밀번호 (Google 계정 설정 -> 보안 -> 앱 비밀번호)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000    # 소켓 타임아웃 5초
          connectiontimeout: 5000 # 연결 타임아웃 5초
          writetimeout: 5000 # 쓰기 타임아웃
jwt:
  secret: DisIsVerySecretKeyForJwtExampleProjectMustBeLongerThan256BitsVoila
